name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_name:
        description: "Docker Image Name (e.g., signals-frontend, signals-backend)"
        required: true
        type: string
      tag:
        description: "Image Tag (e.g., latest, v1.0.0, dev)"
        required: false
        default: "latest"
        type: string


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/amsterdam/signals-frontend-deploy:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/amsterdam/signals-frontend-deploy:latest

